apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-appp
  template:
    metadata:
      labels:
        app: ip-appp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
