apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-appp
  template:
    metadata:
      labels:
        app: ip-appp
    spec:
      containers:
      - name: ipappp
        image: alpine:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pvc-vol1
          mountPath: /app/pvc-volume
      volumes:
      - name: pvc-vol1
        persistentVolumeClaim:
          claimName: my-pvc1
