apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: sachin-k8
  source:
    repoURL: https://github.com/sachingowda0159/my-repo.git
    targetRevision: main
    path: argocd/kube_configs
  destination:
    server: https://13.201.8.19:6443
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
